### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by erolrecep** [aritter/twitter_download#2]
I'm not able to open this [link](https://www.cs.york.ac.uk/semeval-2013/task2/index.php?id=data). Is there any problem on link or just on my computer?

**Comment by drevicko** [comment]
fwiw, semeval 2015 used the same data. Links to download are here;

http://alt.qcri.org/semeval2015/task10/index.php?id=data-and-tools

**Comment by erolrecep** [comment]
Thank you.
