### ISSUE TITLE
What should be tweeti-a.dist.tsv?

### ISSUE THREAD

**Issue by jzhoubu** [aritter/twitter_download#5]
I tried the training data as tweeti-a.dist.tsv (each row like this "628949369883000832 @microsoft negative").But it goes worry in both python2.7 and python3.5.

**Comment by viktorm8** [comment]
where I can take this .tsv file???

**Comment by MarianaLeal** [comment]
When reading the code, it seems like they are expecting that the first 2 parameters in each row are id of each tweet. So each line of the tsv file you give must be something like "12383893 183832 @microsoft negative". 
However, the second id (what they called 'uid') is not used with the _api script, so I guess you can just comment the line 'uid = fields[1]'.

**Comment by NatashaSvic** [comment]
I get this error when running the script: _No such file or directory: 'tweeti-a.dist.tsv'_. Where can I find the file or, how is it created? Thank you!!

twitter_download-master natasha$ python download_tweets_api.py --dist=tweeti-a.dist.tsv --output=downloaded.tsv

Started at 2018-06-29 22:29:11.794779
usage: download_tweets_api.py [-h] [--partial PARTIAL] --dist DIST --output
                              OUTPUTPATH
download_tweets_api.py: error: argument --dist: can't open 'tweeti-a.dist.tsv': [Errno 2] No such file or directory: 'tweeti-a.dist.tsv'
